### ISSUE TITLE
PCHViewer

### ISSUE THREAD

**Issue by AlanDrake** [pachuco/Shi-PaintAndChat#2]
You've forgotten about the poor PCHViewer.
I've tried decompiling it the same way, I had to add your LComponent thing and then overwrite some of the "paintchat" files with the ones you modified (I kept the java.Applet import), since it wouldn't start drawing otherwise.

It actually works... A surprise since I haven't touched java for more than a decade.

I've been looking into this stuff for nostalgia. I wanted to see the feasibility of running them through CheerpJ or a javascript rewrite now that the times are ripe for the PointerEvents and a japanese dev is remaking PaintBBS on js.

**Comment by pachuco** [comment]
I remember trying at one point CheepJ and ShiPainter worked, albeit a few orders of magnitude slower.

PCHViewer houses two applets with three playback engines(original PaintBBS(MgLine) applet; old ShiPainter(Mg) + new ShiPainter(M) applet).
Mg playback is a bit borked and requires loading a dummy spch file to appease its bugs. Didn't feel like adding PCHViewer to my already convoluted mix.

The project has been sitting in apathy and dust for the last 6 months, but with reappearance of interest, I might get off me bumarse and return to it.

**Comment by AlanDrake** [comment]
ShiPainter goes very well with CheerpJ 1.3, in theory once it fully transition to webassembly the PCHViewer might even become viable.

Anyway, at this point I'm wondering if it wouldn't be the case to just cram everything into the same repository, maybe separating the Idea project in multiple modules.
All Shi-chan's stuff shares pieces of the same codebase, and we need to clean up the shared pieces anyway. That way we could kill five birds with one stone.
